name: jdk-compat

on:
  push:
    branches: [ develop ]

jobs:
  build:
    timeout-minutes: 10
    runs-on: ubuntu-latest
    steps:
    - name: git checkout
      uses: actions/checkout@v2
    - name: get latest jdk ga
      uses: sormuras/download-jdk@v1
      with:
        feature: 19
    - name: set up jdk
      uses: actions/setup-java@v2
      with:
        distribution: jdkfile
        jdkFile: ${{ env.JDK_FILE }}
        java-version: ${{ env.JDK_VERSION }}      
    - name: cache maven packages
      uses: actions/cache@v2
      with:
        path: ~/.m2/repository
        key: ${{ runner.os }}-maven-${{ hashFiles('**/pom.xml') }}
        restore-keys: ${{ runner.os }}-maven-
    - name: build with maven
      run: mvn -B clean install -P pre-release -Djavacpp.platform=linux-x86_64
