name: maven-release

on:
  workflow_dispatch:
    inputs:
      version:
        description: version
        required: true
        default: 'X.X.X.RCX'

jobs:
  build:
    timeout-minutes: 20
    runs-on: ubuntu-latest
    steps:
    - name: git checkout
      uses: actions/checkout@v2
    - name: set up jdk 8
      uses: actions/setup-java@v2
      with:
        distribution: adopt
        java-version: 8
        server-id: ossrh
        server-username: MAVEN_USERNAME
        server-password: MAVEN_PASSWORD
        gpg-private-key: ${{ secrets.OSSRH_GPG_SECRET_KEY }}
        gpg-passphrase: MAVEN_GPG_PASSPHRASE
    - name: set maven version
      run: |
        mvn versions:set versions:commit -DnewVersion=${{ github.event.inputs.version }}
    - name: docker build
      run: |
        mvn clean install -P pre-release -DskipTests
        ./build-docker.sh
        docker tag karate-chrome ptrthomas/karate-chrome:latest
        docker tag karate-chrome ptrthomas/karate-chrome:${{ github.event.inputs.version }}
    # - name: docker login
    #   uses: docker/login-action@f054a8b539a109f9f41c372932f1ae047eff08c9
    #   with:
    #     username: ${{ secrets.DOCKER_USERNAME }}
    #     password: ${{ secrets.DOCKER_PASSWORD }}
    # - name: docker push
    #   run: |
    #     docker push ptrthomas/karate-chrome:${{ github.event.inputs.version }}    
    # - name: maven deploy to central
    #   env:
    #     MAVEN_USERNAME: ${{ secrets.OSSRH_USERNAME }}
    #     MAVEN_PASSWORD: ${{ secrets.OSSRH_TOKEN }}
    #     MAVEN_GPG_PASSPHRASE: ${{ secrets.OSSRH_GPG_SECRET_KEY_PASSWORD }}
    #   run: |
    #     mvn \
    #       --no-transfer-progress \
    #       --batch-mode \
    #       clean deploy -P pre-release,release
    - name: maven build binaries
      run: |
        mvn clean package -P fatjar -f karate-core/pom.xml
        mvn clean package -P fatjar -f karate-robot/pom.xml
    - name: upload binaries
      uses: actions/upload-artifact@v3
      with: 
        name: karate-${{ github.event.inputs.version }}
        retention-days: 5 
        path: |
          karate-core/target
          karate-robot/target
          karate-e2e-tests/target          
