name: maven-release

on:
  workflow_dispatch:
    inputs:
      version:
        description: version
        required: true
        default: 'X.X.X.RCX'

jobs:
  build:
    timeout-minutes: 20
    runs-on: ubuntu-20.04
    steps:
    - name: git checkout
      uses: actions/checkout@v2    
    - name: set up jdk 8
      uses: actions/setup-java@v2
      with:
        distribution: adopt
        java-version: 8
        server-id: ossrh
        server-username: MAVEN_USERNAME
        server-password: MAVEN_PASSWORD        
    - name: cache maven packages
      uses: actions/cache@v2
      with:
        path: ~/.m2
        key: ${{ runner.os }}-m2-${{ hashFiles('**/pom.xml') }}
        restore-keys: ${{ runner.os }}-m2
    - name: install gpg secret key
      run: |
        cat <(echo -e "${{ secrets.OSSRH_GPG_SECRET_KEY }}") | gpg --batch --import
        gpg --list-secret-keys --keyid-format LONG        
    - name: set maven version
      run: |
        mvn versions:set -DnewVersion=${{ github.event.inputs.version }}
        mvn versions:commit
    - name: maven deploy to central
      env:
        MAVEN_USERNAME: ${{ secrets.OSSRH_USERNAME }}
        MAVEN_PASSWORD: ${{ secrets.OSSRH_TOKEN }}
      run: |
        mvn \
          --no-transfer-progress \
          --batch-mode \
          -Dgpg.passphrase=${{ secrets.OSSRH_GPG_SECRET_KEY_PASSWORD }} \
          clean deploy -P pre-release,release -Djavacpp.platform=linux-x86_64 -DskipRemoteStaging=true
