name: maven-release

on:
  workflow_dispatch:
    inputs:
      version:
        description: version
        required: true
        default: 'X.X.X.RCX'

jobs:
  build:
    timeout-minutes: 20
    runs-on: ubuntu-latest
    steps:
    - name: git checkout
      uses: actions/checkout@v2    
    - name: set up jdk 8
      uses: actions/setup-java@v2
      with:
        distribution: adopt
        java-version: 8
        server-id: ossrh
        server-username: MAVEN_USERNAME
        server-password: MAVEN_PASSWORD
        gpg-private-key: ${{ secrets.OSSRH_GPG_SECRET_KEY }}
        gpg-passphrase: MAVEN_GPG_PASSPHRASE      
    - name: set maven version
      run: |
        mvn versions:set -DnewVersion=${{ github.event.inputs.version }}
        mvn versions:commit
    - name: maven deploy to central
      env:
        MAVEN_USERNAME: ${{ secrets.OSSRH_USERNAME }}
        MAVEN_PASSWORD: ${{ secrets.OSSRH_TOKEN }}
        MAVEN_GPG_PASSPHRASE: ${{ secrets.OSSRH_GPG_SECRET_KEY_PASSWORD }}
      run: |
        mvn \
          --no-transfer-progress \
          --batch-mode \
          clean deploy -P pre-release,release -DskipRemoteStaging=true
